### ISSUE TITLE
[Suggestion] Avoid providing actual ROM Files

### ISSUE THREAD

**Issue by LOuroboros** [nielsmittertreiner/pokemon-skyline#1]
I suggest you to avoid providing GBA ROM Files in your repository. I don't know if you're aware, but **they're at the mercy of DMCA Takedown requests**, just like it happened to a GameBoy Emulator fairly recently [as you can see right here](https://torrentfreak.com/nintendo-asks-github-to-remove-game-boy-emulator-180723/).

Considering that you have expanded the size of your ROM, you should use .ups patches instead.

**Comment by nielsmittertreiner** [comment]
Thanks! Now that you mention it, it's really stupid of me, I guess it didn't cross my mind earlier.

**Comment by nielsmittertreiner** [comment]
@LOuroboros Do you know any way how to smoothly prevent any push and pulling issues with the ups/ips patch with more than one dev? We have the roms on different locations apart from this one
